name: Build Go binaries

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: GOOS=linux GOARCH=arm go build

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ${{ github.workspace }}/*
