name: Build Go binaries

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: sosedoff/actions/golang-build@master
        with:
          args: linux/arm

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ${{ github.workspace }}/.release/*
